name: push_message_sender
description: A starting point for Dart libraries or applications.
maintainer: Alexander Bosak (bskaxe@gmail.com)
homepage: https://github.com/cyrax111/push_message_sender
issue_tracker: https://github.com/cyrax111/push_message_sender/issues
version: 0.5.3

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  http: ^0.13.5
  meta: ^1.8.0
  emptyable_timer: ^0.0.1
  jwt_manager: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
